version: '3'
services:
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
  api:
    build: .
    command: bash -c "rm -f /tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/plume
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - .env