---
swagger: '2.0'
info:
  title: API V1
  version: v1
basePath: "/v1"
servers:
- url: "/v1"
  description: v1 of the API spec
- url: "/v2"
  description: v2 of the API spec
components:
  securitySchemes:
    bearer:
      type: apiKey
      name: Authorization
      in: header
definitions:
  user_login:
    type: object
    properties:
      user:
        type: object
        properties:
          email:
            type: string
          password:
            type: string
    required:
    - user
  user:
    type: object
    properties:
      user:
        type: object
        properties:
          email:
            type: string
          password:
            type: string
          full_name:
            type: string
paths:
  "/auth/login":
    post:
      summary: Logs in a user
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user
        in: body
        required: true
        schema:
          "$ref": "#/definitions/user_login"
      responses:
        '200':
          description: Sign in successful
        '401':
          description: Unauthorized
  "/auth/signup":
    post:
      summary: Register a new user
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user
        in: body
        required: true
        schema:
          "$ref": "#/definitions/user"
      responses:
        '200':
          description: User created
        '422':
          description: Fails when full name contains no space
