---
swagger: '2.0'
info:
  title: API V1
  version: v1
basePath: "/v1"
servers:
- url: "/v1"
  description: v1 of the API spec
- url: "/v2"
  description: v2 of the API spec
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
definitions:
  user:
    type: object
    properties:
      user:
        type: object
        properties:
          email:
            type: string
          password:
            type: string
    required:
    - user
paths:
  "/auth/login":
    post:
      summary: Logs in a user
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      parameters:
      - name: user
        in: body
        required: true
        schema:
          "$ref": "#/definitions/user"
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  "/businesses":
    get:
      summary: List all businesses
      parameters:
      - name: page
        in: query
      responses:
        '200':
          description: success
    post:
      summary: Creates a new business
      consumes:
      - application/json
      security:
      - bearerAuth: []
      parameters:
      - name: business
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            logo:
              type: string
            description:
              type: string
            main_address:
              type: string
            phone:
              type: string
          required:
          - name
          - main_address
      responses:
        '201':
          description: business created
        '422':
          description: invalid request
