---
openapi: 3.0.1
info:
  title: API V1
  version: v1
servers:
- url: "/v1"
  description: v1 of the API spec
- url: "/v2"
  description: v2 of the API spec
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/auth/login":
    post:
      summary: Logs in a user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: Success
  "/businesses":
    get:
      summary: List all businesses
      parameters:
      - name: page
        in: query
      responses:
        '200':
          description: success
    post:
      summary: Creates a new business
      consumes:
      - application/json
      security:
      - bearerAuth: []
      parameters:
      - name: business
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            logo:
              type: string
            description:
              type: string
            main_address:
              type: string
            phone:
              type: string
          required:
          - name
          - main_address
      responses:
        '201':
          description: business created
        '422':
          description: invalid request
